spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql:///resource_com?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 
    password: 
    type: com.alibaba.druid.pool.DruidDataSource


